// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu-clgzLX1ctZVKQGFlQTn-0esbHMuwCU',
    appId: '1:290016369962:web:145a3c0ffd88032df85253',
    messagingSenderId: '290016369962',
    projectId: 'memegen-bbf32',
    authDomain: 'memegen-bbf32.firebaseapp.com',
    storageBucket: 'memegen-bbf32.appspot.com',
    measurementId: 'G-243Z9N2M84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu-clgzLX1ctZVKQGFlQTn-0esbHMuwCU',
    appId: '1:508219930254:android:5fec02bfc0d94b88013bdf',
    messagingSenderId: '508219930254',
    projectId: 'memegenfrontend',
    storageBucket: 'memegenfrontend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu-clgzLX1ctZVKQGFlQTn-0esbHMuwCU',
    appId: '1:290016369962:ios:45e972388e223954f85253',
    messagingSenderId: '290016369962',
    projectId: 'memegen-bbf32',
    storageBucket: 'memegen-bbf32.appspot.com',
    iosBundleId: 'com.example.memeApp',
  );
}
